export const reminder_default_img = 'cloud://ldh-xinaa.6c64-ldh-xinaa-1259815928/CPD/rar_plan/default.png'
export const record__default_img = 'cloud://ldh-xinaa.6c64-ldh-xinaa-1259815928/CPD/rar_record/jilu_default.png'
export const pet_avatar = 'CPD/pet_avatar/'
export const record_picture = 'CPD/record_picture/'
export const templateId = 'kqHePUKZxtp8JTF5AHvrCgAdYUib7u2pMsCdBdoD5GQ'